# -*- coding: utf-8 -*-
"""deploy_hbp.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yzr3539BccO06ua3TEtbGXzLFSttuMO3
"""

import streamlit as st
import pickle
from PIL import Image

with open("random_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("HIGH BLOOD PRESSURE")
st.markdown("By preethi")
image = Image.open("1e82b7.webp")
st.image(image, use_column_width=True)

age = st.number_input("Age of a person",min_value=0,max_value=100,value=0)
height = st.number_input("Height of a person",min_value=0,max_value=400,value=0)


if st.button("HyperTension test result"):
   if prediction == 0:
            st.subheader("The person doesn't have Hypertension.")
   elif prediction == 1:
            st.subheader("The person have Hypertension.")
else:
        st.subheader("Please enter a text for prediction.")

